<?php

namespace Database\Seeders;

use App\Models\MicroAction;
use Illuminate\Database\Seeder;

class MicroActionSeeder150New extends Seeder
{
    public function run(): void
    {
        // Очищаем существующие микродействия
        MicroAction::query()->delete();
        
        $microActions = $this->getMicroActionsData();
        
        foreach ($microActions as $actionData) {
            MicroAction::updateOrCreate(
                ['name' => $actionData['name'], 'position' => $actionData['position']],
                $actionData
            );
        }
        
        $this->command->info('Создано ' . count($microActions) . ' микро-действий');
        $personalizedCount = collect($microActions)->whereNotNull('personalization_key')->count();
        $this->command->info('Из них с персонализацией: ' . $personalizedCount);
    }
    
    private function getMicroActionsData(): array
    {
        return [
            // ========== DESKTOP ==========
            ['name' => 'Проверить почту', 'description' => 'Быстро просмотреть входящие письма', 'category' => 'social', 'energy_reward' => 5, 'experience_reward' => 3, 'cooldown_minutes' => 30, 'unlock_level' => 1, 'position' => 'desktop', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Написать заметку', 'description' => 'Записать важную мысль', 'category' => 'social', 'energy_reward' => 8, 'experience_reward' => 5, 'cooldown_minutes' => 20, 'unlock_level' => 1, 'position' => 'desktop', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Просмотреть задачи', 'description' => 'Проверить список дел на сегодня', 'category' => 'social', 'energy_reward' => 6, 'experience_reward' => 4, 'cooldown_minutes' => 25, 'unlock_level' => 1, 'position' => 'desktop', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Послушать {{favorite_song}}', 'description' => 'Включить любимую композицию', 'category' => 'relaxation', 'energy_reward' => 18, 'experience_reward' => 8, 'cooldown_minutes' => 45, 'unlock_level' => 2, 'position' => 'desktop', 'is_active' => true, 'personalization_key' => 'favorite_song'],
            ['name' => 'Создать плейлист с {{favorite_song}}', 'description' => 'Составить музыкальную подборку вокруг любимой композиции', 'category' => 'creativity', 'energy_reward' => 12, 'experience_reward' => 10, 'cooldown_minutes' => 40, 'unlock_level' => 3, 'position' => 'desktop', 'is_active' => true, 'personalization_key' => 'favorite_song'],
            ['name' => 'Найти информацию о книге «{{favorite_book}}»', 'description' => 'Изучить критику и отзывы', 'category' => 'creativity', 'energy_reward' => 8, 'experience_reward' => 10, 'cooldown_minutes' => 25, 'unlock_level' => 2, 'position' => 'desktop', 'is_active' => true, 'personalization_key' => 'favorite_book'],
            ['name' => 'Посмотреть трейлер фильма «{{favorite_movie}}»', 'description' => 'Пересмотреть трейлер любимого фильма', 'category' => 'relaxation', 'energy_reward' => 10, 'experience_reward' => 6, 'cooldown_minutes' => 20, 'unlock_level' => 1, 'position' => 'desktop', 'is_active' => true, 'personalization_key' => 'favorite_movie'],
            ['name' => 'Поискать рецепт {{favorite_dish}}', 'description' => 'Найти способ приготовления любимого блюда', 'category' => 'exercise', 'energy_reward' => 12, 'experience_reward' => 8, 'cooldown_minutes' => 30, 'unlock_level' => 2, 'position' => 'desktop', 'is_active' => true, 'personalization_key' => 'favorite_dish'],
            ['name' => 'Написать другу {{best_friend_name}}', 'description' => 'Твой друг {{best_friend_name}} будет рад получить сообщение', 'category' => 'social', 'energy_reward' => 15, 'experience_reward' => 10, 'cooldown_minutes' => 45, 'unlock_level' => 1, 'position' => 'desktop', 'is_active' => true, 'personalization_key' => 'best_friend_name'],
            ['name' => 'Посмотреть видео', 'description' => 'Короткий образовательный ролик', 'category' => 'creativity', 'energy_reward' => 8, 'experience_reward' => 12, 'cooldown_minutes' => 35, 'unlock_level' => 2, 'position' => 'desktop', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Обновить документ', 'description' => 'Внести правки в рабочий файл', 'category' => 'social', 'energy_reward' => 10, 'experience_reward' => 8, 'cooldown_minutes' => 40, 'unlock_level' => 3, 'position' => 'desktop', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Провести видеозвонок', 'description' => 'Быстрая онлайн-встреча', 'category' => 'social', 'energy_reward' => 12, 'experience_reward' => 10, 'cooldown_minutes' => 60, 'unlock_level' => 5, 'position' => 'desktop', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Написать отзыв на книгу «{{favorite_book}}»', 'description' => 'Поделиться впечатлениями о прочитанном', 'category' => 'social', 'energy_reward' => 14, 'experience_reward' => 12, 'cooldown_minutes' => 60, 'unlock_level' => 4, 'position' => 'desktop', 'is_active' => true, 'personalization_key' => 'favorite_book'],
            ['name' => 'Написать рецензию на фильм «{{favorite_movie}}»', 'description' => 'Проанализировать просмотренное', 'category' => 'creativity', 'energy_reward' => 16, 'experience_reward' => 14, 'cooldown_minutes' => 60, 'unlock_level' => 5, 'position' => 'desktop', 'is_active' => true, 'personalization_key' => 'favorite_movie'],
            ['name' => 'Организовать файлы', 'description' => 'Навести порядок на рабочем столе', 'category' => 'social', 'energy_reward' => 8, 'experience_reward' => 5, 'cooldown_minutes' => 30, 'unlock_level' => 2, 'position' => 'desktop', 'is_active' => true, 'personalization_key' => null],

            // ========== PHONE ==========
            ['name' => 'Ответить на сообщение', 'description' => 'Написать другу в мессенджере', 'category' => 'social', 'energy_reward' => 7, 'experience_reward' => 4, 'cooldown_minutes' => 15, 'unlock_level' => 1, 'position' => 'phone', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Позвонить другу {{best_friend_name}}', 'description' => 'Твой друг {{best_friend_name}} будет рад услышать твой голос', 'category' => 'social', 'energy_reward' => 20, 'experience_reward' => 15, 'cooldown_minutes' => 90, 'unlock_level' => 2, 'position' => 'phone', 'is_active' => true, 'personalization_key' => 'best_friend_name'],
            ['name' => 'Позвонить близкому', 'description' => 'Короткий звонок родным', 'category' => 'social', 'energy_reward' => 15, 'experience_reward' => 10, 'cooldown_minutes' => 45, 'unlock_level' => 1, 'position' => 'phone', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Написать другу {{best_friend_name}}', 'description' => 'Отправить сообщение лучшему другу', 'category' => 'social', 'energy_reward' => 12, 'experience_reward' => 8, 'cooldown_minutes' => 30, 'unlock_level' => 1, 'position' => 'phone', 'is_active' => true, 'personalization_key' => 'best_friend_name'],
            ['name' => 'Послушать {{favorite_song}}', 'description' => 'Включить любимую композицию', 'category' => 'relaxation', 'energy_reward' => 16, 'experience_reward' => 7, 'cooldown_minutes' => 40, 'unlock_level' => 1, 'position' => 'phone', 'is_active' => true, 'personalization_key' => 'favorite_song'],
            ['name' => 'Послушать подкаст', 'description' => 'Включить образовательный подкаст', 'category' => 'creativity', 'energy_reward' => 12, 'experience_reward' => 14, 'cooldown_minutes' => 50, 'unlock_level' => 4, 'position' => 'phone', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Прочитать статью', 'description' => 'Изучить интересный материал', 'category' => 'creativity', 'energy_reward' => 8, 'experience_reward' => 15, 'cooldown_minutes' => 30, 'unlock_level' => 3, 'position' => 'phone', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Прокрутить ленту', 'description' => 'Посмотреть новости в соцсетях', 'category' => 'relaxation', 'energy_reward' => 5, 'experience_reward' => 2, 'cooldown_minutes' => 20, 'unlock_level' => 1, 'position' => 'phone', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Сделать селфи', 'description' => 'Запечатлеть настроение', 'category' => 'creativity', 'energy_reward' => 10, 'experience_reward' => 6, 'cooldown_minutes' => 25, 'unlock_level' => 2, 'position' => 'phone', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Установить будильник', 'description' => 'Настроить напоминание', 'category' => 'social', 'energy_reward' => 5, 'experience_reward' => 3, 'cooldown_minutes' => 10, 'unlock_level' => 1, 'position' => 'phone', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Отправить фото другу {{best_friend_name}}', 'description' => 'Твой друг {{best_friend_name}} будет рад увидеть твои фото', 'category' => 'social', 'energy_reward' => 14, 'experience_reward' => 9, 'cooldown_minutes' => 35, 'unlock_level' => 2, 'position' => 'phone', 'is_active' => true, 'personalization_key' => 'best_friend_name'],
            ['name' => 'Поискать обсуждения книги «{{favorite_book}}»', 'description' => 'Найти форумы читателей', 'category' => 'social', 'energy_reward' => 10, 'experience_reward' => 12, 'cooldown_minutes' => 30, 'unlock_level' => 3, 'position' => 'phone', 'is_active' => true, 'personalization_key' => 'favorite_book'],
            ['name' => 'Посмотреть актеров из фильма «{{favorite_movie}}»', 'description' => 'Изучить информацию о фильме', 'category' => 'creativity', 'energy_reward' => 12, 'experience_reward' => 10, 'cooldown_minutes' => 35, 'unlock_level' => 2, 'position' => 'phone', 'is_active' => true, 'personalization_key' => 'favorite_movie'],
            ['name' => 'Записать голосовую заметку', 'description' => 'Сохранить идею на диктофон', 'category' => 'creativity', 'energy_reward' => 7, 'experience_reward' => 5, 'cooldown_minutes' => 15, 'unlock_level' => 2, 'position' => 'phone', 'is_active' => true, 'personalization_key' => null],

            // ========== TABLET ==========
            ['name' => 'Порисовать', 'description' => 'Набросать скетч на планшете', 'category' => 'creativity', 'energy_reward' => 15, 'experience_reward' => 12, 'cooldown_minutes' => 40, 'unlock_level' => 3, 'position' => 'tablet', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Прочитать книгу', 'description' => 'Несколько страниц любимого романа', 'category' => 'creativity', 'energy_reward' => 18, 'experience_reward' => 15, 'cooldown_minutes' => 45, 'unlock_level' => 2, 'position' => 'tablet', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Почитать книгу «{{favorite_book}}»', 'description' => 'Погрузиться в любимую книгу', 'category' => 'creativity', 'energy_reward' => 20, 'experience_reward' => 18, 'cooldown_minutes' => 60, 'unlock_level' => 2, 'position' => 'tablet', 'is_active' => true, 'personalization_key' => 'favorite_book'],
            ['name' => 'Перечитать любимую главу из книги «{{favorite_book}}»', 'description' => 'Вернуться к любимому моменту', 'category' => 'relaxation', 'energy_reward' => 16, 'experience_reward' => 12, 'cooldown_minutes' => 50, 'unlock_level' => 3, 'position' => 'tablet', 'is_active' => true, 'personalization_key' => 'favorite_book'],
            ['name' => 'Изучить иллюстрации к книге «{{favorite_book}}»', 'description' => 'Посмотреть арт к любимой книге', 'category' => 'creativity', 'energy_reward' => 12, 'experience_reward' => 14, 'cooldown_minutes' => 40, 'unlock_level' => 4, 'position' => 'tablet', 'is_active' => true, 'personalization_key' => 'favorite_book'],
            ['name' => 'Посмотреть рецепты', 'description' => 'Найти идею для ужина', 'category' => 'exercise', 'energy_reward' => 8, 'experience_reward' => 6, 'cooldown_minutes' => 25, 'unlock_level' => 1, 'position' => 'tablet', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Рецепт {{favorite_dish}}', 'description' => 'Изучить способ приготовления', 'category' => 'exercise', 'energy_reward' => 15, 'experience_reward' => 10, 'cooldown_minutes' => 40, 'unlock_level' => 2, 'position' => 'tablet', 'is_active' => true, 'personalization_key' => 'favorite_dish'],
            ['name' => 'Играть в игру', 'description' => 'Расслабляющая мобильная игра', 'category' => 'relaxation', 'energy_reward' => 12, 'experience_reward' => 5, 'cooldown_minutes' => 30, 'unlock_level' => 1, 'position' => 'tablet', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Составить план', 'description' => 'Записать цели на неделю', 'category' => 'social', 'energy_reward' => 10, 'experience_reward' => 10, 'cooldown_minutes' => 35, 'unlock_level' => 2, 'position' => 'tablet', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Медитировать', 'description' => 'Запустить приложение для медитации', 'category' => 'relaxation', 'energy_reward' => 20, 'experience_reward' => 8, 'cooldown_minutes' => 60, 'unlock_level' => 5, 'position' => 'tablet', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Решить судоку', 'description' => 'Тренировка логического мышления', 'category' => 'creativity', 'energy_reward' => 10, 'experience_reward' => 12, 'cooldown_minutes' => 30, 'unlock_level' => 3, 'position' => 'tablet', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Составить список книг к прочтению', 'description' => 'Планирование литературного развития', 'category' => 'creativity', 'energy_reward' => 12, 'experience_reward' => 10, 'cooldown_minutes' => 60, 'unlock_level' => 4, 'position' => 'tablet', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Читать цитаты из книги «{{favorite_book}}»', 'description' => 'Вдохновиться мудрыми мыслями', 'category' => 'relaxation', 'energy_reward' => 14, 'experience_reward' => 11, 'cooldown_minutes' => 35, 'unlock_level' => 3, 'position' => 'tablet', 'is_active' => true, 'personalization_key' => 'favorite_book'],
            ['name' => 'Посмотреть обучающий курс', 'description' => 'Изучить новую тему', 'category' => 'creativity', 'energy_reward' => 15, 'experience_reward' => 16, 'cooldown_minutes' => 50, 'unlock_level' => 4, 'position' => 'tablet', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Поиграть в головоломку', 'description' => 'Тренировка ума', 'category' => 'creativity', 'energy_reward' => 11, 'experience_reward' => 13, 'cooldown_minutes' => 30, 'unlock_level' => 3, 'position' => 'tablet', 'is_active' => true, 'personalization_key' => null],

            // ========== TV ==========
            ['name' => 'Посмотреть фильм', 'description' => 'Включить интересное кино', 'category' => 'relaxation', 'energy_reward' => 25, 'experience_reward' => 10, 'cooldown_minutes' => 120, 'unlock_level' => 1, 'position' => 'tv', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Посмотреть фильм «{{favorite_movie}}»', 'description' => 'Пересмотреть любимый фильм', 'category' => 'relaxation', 'energy_reward' => 30, 'experience_reward' => 15, 'cooldown_minutes' => 150, 'unlock_level' => 1, 'position' => 'tv', 'is_active' => true, 'personalization_key' => 'favorite_movie'],
            ['name' => 'Пересмотреть фильм «{{favorite_movie}}»', 'description' => 'Ностальгическая терапия и приятные воспоминания', 'category' => 'relaxation', 'energy_reward' => 28, 'experience_reward' => 12, 'cooldown_minutes' => 180, 'unlock_level' => 3, 'position' => 'tv', 'is_active' => true, 'personalization_key' => 'favorite_movie'],
            ['name' => 'Посмотреть новости', 'description' => 'Узнать о событиях дня', 'category' => 'creativity', 'energy_reward' => 8, 'experience_reward' => 8, 'cooldown_minutes' => 30, 'unlock_level' => 1, 'position' => 'tv', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Посмотреть сериал', 'description' => 'Продолжить любимый сериал', 'category' => 'relaxation', 'energy_reward' => 20, 'experience_reward' => 8, 'cooldown_minutes' => 60, 'unlock_level' => 2, 'position' => 'tv', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Заниматься йогой', 'description' => 'Включить видео с упражнениями', 'category' => 'exercise', 'energy_reward' => 30, 'experience_reward' => 15, 'cooldown_minutes' => 90, 'unlock_level' => 4, 'position' => 'tv', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Посмотреть документалку', 'description' => 'Познавательный фильм', 'category' => 'creativity', 'energy_reward' => 15, 'experience_reward' => 20, 'cooldown_minutes' => 75, 'unlock_level' => 3, 'position' => 'tv', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Караоке', 'description' => 'Спеть любимую песню', 'category' => 'creativity', 'energy_reward' => 18, 'experience_reward' => 10, 'cooldown_minutes' => 45, 'unlock_level' => 2, 'position' => 'tv', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Спеть {{favorite_song}}', 'description' => 'Исполнить любимую композицию', 'category' => 'creativity', 'energy_reward' => 20, 'experience_reward' => 12, 'cooldown_minutes' => 50, 'unlock_level' => 2, 'position' => 'tv', 'is_active' => true, 'personalization_key' => 'favorite_song'],
            ['name' => 'Посмотреть клип на {{favorite_song}}', 'description' => 'Насладиться визуализацией любимой песни', 'category' => 'relaxation', 'energy_reward' => 16, 'experience_reward' => 9, 'cooldown_minutes' => 40, 'unlock_level' => 2, 'position' => 'tv', 'is_active' => true, 'personalization_key' => 'favorite_song'],
            ['name' => 'Посмотреть стрим', 'description' => 'Подключиться к трансляции', 'category' => 'social', 'energy_reward' => 12, 'experience_reward' => 7, 'cooldown_minutes' => 40, 'unlock_level' => 1, 'position' => 'tv', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Посмотреть документальный фильм', 'description' => 'Образовательный контент на 40-60 минут', 'category' => 'creativity', 'energy_reward' => 18, 'experience_reward' => 20, 'cooldown_minutes' => 120, 'unlock_level' => 3, 'position' => 'tv', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Посмотреть фильм «{{favorite_movie}}» с другом {{best_friend_name}}', 'description' => 'Твой друг {{best_friend_name}} будет рад совместному просмотру', 'category' => 'social', 'energy_reward' => 32, 'experience_reward' => 18, 'cooldown_minutes' => 180, 'unlock_level' => 4, 'position' => 'tv', 'is_active' => true, 'personalization_key' => 'favorite_movie'],
            ['name' => 'Посмотреть фильм похожий на «{{favorite_movie}}»', 'description' => 'Открыть для себя новое кино', 'category' => 'creativity', 'energy_reward' => 22, 'experience_reward' => 16, 'cooldown_minutes' => 150, 'unlock_level' => 5, 'position' => 'tv', 'is_active' => true, 'personalization_key' => 'favorite_movie'],
            ['name' => 'Посмотреть иностранный фильм с субтитрами', 'description' => 'Погружение в другую культуру', 'category' => 'creativity', 'energy_reward' => 18, 'experience_reward' => 16, 'cooldown_minutes' => 180, 'unlock_level' => 6, 'position' => 'tv', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Марафон короткометражек', 'description' => 'Посмотреть 3-4 короткометражных фильма', 'category' => 'relaxation', 'energy_reward' => 20, 'experience_reward' => 16, 'cooldown_minutes' => 120, 'unlock_level' => 5, 'position' => 'tv', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Посмотреть концерт', 'description' => 'Живое выступление музыкантов', 'category' => 'relaxation', 'energy_reward' => 22, 'experience_reward' => 14, 'cooldown_minutes' => 100, 'unlock_level' => 4, 'position' => 'tv', 'is_active' => true, 'personalization_key' => null],

            // ========== SPEAKER ==========
            ['name' => 'Послушать аудиокнигу', 'description' => 'Включить захватывающий роман', 'category' => 'creativity', 'energy_reward' => 15, 'experience_reward' => 15, 'cooldown_minutes' => 60, 'unlock_level' => 2, 'position' => 'speaker', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Послушать книгу «{{favorite_book}}»', 'description' => 'Аудиоверсия любимой книги', 'category' => 'creativity', 'energy_reward' => 18, 'experience_reward' => 18, 'cooldown_minutes' => 75, 'unlock_level' => 2, 'position' => 'speaker', 'is_active' => true, 'personalization_key' => 'favorite_book'],
            ['name' => 'Включить радио', 'description' => 'Послушать музыкальную волну', 'category' => 'relaxation', 'energy_reward' => 10, 'experience_reward' => 5, 'cooldown_minutes' => 30, 'unlock_level' => 1, 'position' => 'speaker', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Послушать {{favorite_song}}', 'description' => 'Включить любимую композицию', 'category' => 'relaxation', 'energy_reward' => 16, 'experience_reward' => 8, 'cooldown_minutes' => 40, 'unlock_level' => 1, 'position' => 'speaker', 'is_active' => true, 'personalization_key' => 'favorite_song'],
            ['name' => 'Создать плейлист с {{favorite_song}}', 'description' => 'Составить музыкальную коллекцию', 'category' => 'creativity', 'energy_reward' => 14, 'experience_reward' => 11, 'cooldown_minutes' => 50, 'unlock_level' => 3, 'position' => 'speaker', 'is_active' => true, 'personalization_key' => 'favorite_song'],
            ['name' => 'Послушать природу', 'description' => 'Звуки дождя и леса', 'category' => 'relaxation', 'energy_reward' => 18, 'experience_reward' => 8, 'cooldown_minutes' => 45, 'unlock_level' => 3, 'position' => 'speaker', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Включить лекцию', 'description' => 'Образовательная аудиозапись', 'category' => 'creativity', 'energy_reward' => 12, 'experience_reward' => 18, 'cooldown_minutes' => 50, 'unlock_level' => 4, 'position' => 'speaker', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Послушать комедию', 'description' => 'Аудио стендап', 'category' => 'relaxation', 'energy_reward' => 14, 'experience_reward' => 7, 'cooldown_minutes' => 35, 'unlock_level' => 2, 'position' => 'speaker', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Послушать подкаст о саморазвитии', 'description' => '20 минут образовательного контента', 'category' => 'relaxation', 'energy_reward' => 18, 'experience_reward' => 12, 'cooldown_minutes' => 90, 'unlock_level' => 1, 'position' => 'speaker', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Прослушать классическую музыку', 'description' => '30 минут спокойной инструментальной музыки', 'category' => 'relaxation', 'energy_reward' => 16, 'experience_reward' => 10, 'cooldown_minutes' => 90, 'unlock_level' => 3, 'position' => 'speaker', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Послушать биографию автора книги «{{favorite_book}}»', 'description' => 'Узнать больше о создателе любимой книги', 'category' => 'creativity', 'energy_reward' => 18, 'experience_reward' => 16, 'cooldown_minutes' => 120, 'unlock_level' => 5, 'position' => 'speaker', 'is_active' => true, 'personalization_key' => 'favorite_book'],
            ['name' => 'Послушать саундтрек к фильму «{{favorite_movie}}»', 'description' => 'Окунуться в атмосферу фильма', 'category' => 'relaxation', 'energy_reward' => 17, 'experience_reward' => 13, 'cooldown_minutes' => 60, 'unlock_level' => 3, 'position' => 'speaker', 'is_active' => true, 'personalization_key' => 'favorite_movie'],
            ['name' => 'Послушать стендап комедию', 'description' => 'Смех - лучшее лекарство от стресса', 'category' => 'relaxation', 'energy_reward' => 18, 'experience_reward' => 10, 'cooldown_minutes' => 60, 'unlock_level' => 5, 'position' => 'speaker', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Послушать ambient музыку для фокуса', 'description' => 'Фоновая музыка для концентрации', 'category' => 'relaxation', 'energy_reward' => 14, 'experience_reward' => 8, 'cooldown_minutes' => 90, 'unlock_level' => 6, 'position' => 'speaker', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Включить альбом исполнителя {{favorite_song}}', 'description' => 'Погрузиться в творчество любимого артиста', 'category' => 'creativity', 'energy_reward' => 19, 'experience_reward' => 14, 'cooldown_minutes' => 75, 'unlock_level' => 4, 'position' => 'speaker', 'is_active' => true, 'personalization_key' => 'favorite_song'],

            // ========== BOOKSHELF ==========
            ['name' => 'Взять книгу с полки', 'description' => 'Достать интересное издание', 'category' => 'creativity', 'energy_reward' => 5, 'experience_reward' => 8, 'cooldown_minutes' => 20, 'unlock_level' => 1, 'position' => 'bookshelf', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Найти книгу «{{favorite_book}}»', 'description' => 'Достать с полки любимую книгу', 'category' => 'creativity', 'energy_reward' => 8, 'experience_reward' => 10, 'cooldown_minutes' => 25, 'unlock_level' => 1, 'position' => 'bookshelf', 'is_active' => true, 'personalization_key' => 'favorite_book'],
            ['name' => 'Перечитать любимую главу', 'description' => 'Вернуться к любимому моменту', 'category' => 'relaxation', 'energy_reward' => 15, 'experience_reward' => 10, 'cooldown_minutes' => 40, 'unlock_level' => 2, 'position' => 'bookshelf', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Перечитать главу из книги «{{favorite_book}}»', 'description' => 'Вернуться к любимому моменту', 'category' => 'relaxation', 'energy_reward' => 18, 'experience_reward' => 12, 'cooldown_minutes' => 45, 'unlock_level' => 2, 'position' => 'bookshelf', 'is_active' => true, 'personalization_key' => 'favorite_book'],
            ['name' => 'Записать цитату', 'description' => 'Выписать мудрую мысль', 'category' => 'creativity', 'energy_reward' => 8, 'experience_reward' => 12, 'cooldown_minutes' => 25, 'unlock_level' => 1, 'position' => 'bookshelf', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Выписать цитату из книги «{{favorite_book}}»', 'description' => 'Сохранить мудрую мысль', 'category' => 'creativity', 'energy_reward' => 10, 'experience_reward' => 14, 'cooldown_minutes' => 30, 'unlock_level' => 2, 'position' => 'bookshelf', 'is_active' => true, 'personalization_key' => 'favorite_book'],
            ['name' => 'Организовать книги', 'description' => 'Навести порядок на полке', 'category' => 'social', 'energy_reward' => 12, 'experience_reward' => 8, 'cooldown_minutes' => 35, 'unlock_level' => 3, 'position' => 'bookshelf', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Почитать поэзию', 'description' => 'Насладиться стихами', 'category' => 'creativity', 'energy_reward' => 14, 'experience_reward' => 15, 'cooldown_minutes' => 30, 'unlock_level' => 2, 'position' => 'bookshelf', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Изучить энциклопедию', 'description' => 'Открыть случайную страницу', 'category' => 'creativity', 'energy_reward' => 10, 'experience_reward' => 18, 'cooldown_minutes' => 35, 'unlock_level' => 4, 'position' => 'bookshelf', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Полистать комиксы', 'description' => 'Легкое чтение с картинками', 'category' => 'relaxation', 'energy_reward' => 12, 'experience_reward' => 6, 'cooldown_minutes' => 25, 'unlock_level' => 1, 'position' => 'bookshelf', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Прочитать главу книги', 'description' => '15-20 минут чтения художественной или научной литературы', 'category' => 'creativity', 'energy_reward' => 12, 'experience_reward' => 15, 'cooldown_minutes' => 60, 'unlock_level' => 1, 'position' => 'bookshelf', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Прочитать главу из книги «{{favorite_book}}»', 'description' => 'Продолжить чтение любимой книги', 'category' => 'creativity', 'energy_reward' => 15, 'experience_reward' => 18, 'cooldown_minutes' => 60, 'unlock_level' => 2, 'position' => 'bookshelf', 'is_active' => true, 'personalization_key' => 'favorite_book'],
            ['name' => 'Разобрать книжную полку', 'description' => 'Навести порядок в библиотеке, отложить ненужное', 'category' => 'exercise', 'energy_reward' => 16, 'experience_reward' => 10, 'cooldown_minutes' => 120, 'unlock_level' => 5, 'position' => 'bookshelf', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Челлендж "Книга за день"', 'description' => 'Прочитать небольшую книгу целиком', 'category' => 'creativity', 'energy_reward' => 30, 'experience_reward' => 25, 'cooldown_minutes' => 240, 'unlock_level' => 7, 'position' => 'bookshelf', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Сортировка книг по жанрам', 'description' => 'Систематизация домашней библиотеки', 'category' => 'creativity', 'energy_reward' => 16, 'experience_reward' => 10, 'cooldown_minutes' => 120, 'unlock_level' => 6, 'position' => 'bookshelf', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Начать читать серию книг', 'description' => 'Погрузиться в многотомную историю', 'category' => 'creativity', 'energy_reward' => 20, 'experience_reward' => 16, 'cooldown_minutes' => 120, 'unlock_level' => 7, 'position' => 'bookshelf', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Организовать буккроссинг', 'description' => 'Обменяться книгами с друзьями или сообществом', 'category' => 'social', 'energy_reward' => 20, 'experience_reward' => 18, 'cooldown_minutes' => 120, 'unlock_level' => 8, 'position' => 'bookshelf', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Подарить книгу «{{favorite_book}}» другу {{best_friend_name}}', 'description' => 'Твой друг {{best_friend_name}} будет рад получить книгу', 'category' => 'social', 'energy_reward' => 22, 'experience_reward' => 16, 'cooldown_minutes' => 180, 'unlock_level' => 5, 'position' => 'bookshelf', 'is_active' => true, 'personalization_key' => 'favorite_book'],
            ['name' => 'Найти книгу похожую на «{{favorite_book}}»', 'description' => 'Открыть для себя новую историю', 'category' => 'creativity', 'energy_reward' => 14, 'experience_reward' => 15, 'cooldown_minutes' => 45, 'unlock_level' => 4, 'position' => 'bookshelf', 'is_active' => true, 'personalization_key' => 'favorite_book'],
            ['name' => 'Изучить биографию автора «{{favorite_book}}»', 'description' => 'Узнать больше о писателе', 'category' => 'creativity', 'energy_reward' => 13, 'experience_reward' => 14, 'cooldown_minutes' => 40, 'unlock_level' => 4, 'position' => 'bookshelf', 'is_active' => true, 'personalization_key' => 'favorite_book'],

            // ========== KITCHEN ==========
            ['name' => 'Приготовить завтрак', 'description' => 'Сделать полезный завтрак', 'category' => 'exercise', 'energy_reward' => 20, 'experience_reward' => 10, 'cooldown_minutes' => 45, 'unlock_level' => 1, 'position' => 'kitchen', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Приготовить {{favorite_dish}}', 'description' => 'Создать любимое блюдо', 'category' => 'exercise', 'energy_reward' => 28, 'experience_reward' => 18, 'cooldown_minutes' => 90, 'unlock_level' => 2, 'position' => 'kitchen', 'is_active' => true, 'personalization_key' => 'favorite_dish'],
            ['name' => 'Заварить чай', 'description' => 'Приготовить ароматный напиток', 'category' => 'exercise', 'energy_reward' => 12, 'experience_reward' => 5, 'cooldown_minutes' => 20, 'unlock_level' => 1, 'position' => 'kitchen', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Приготовить ужин', 'description' => 'Создать кулинарный шедевр', 'category' => 'exercise', 'energy_reward' => 25, 'experience_reward' => 15, 'cooldown_minutes' => 60, 'unlock_level' => 2, 'position' => 'kitchen', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Испечь что-нибудь', 'description' => 'Сладкая выпечка', 'category' => 'creativity', 'energy_reward' => 22, 'experience_reward' => 18, 'cooldown_minutes' => 70, 'unlock_level' => 4, 'position' => 'kitchen', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Сделать смузи', 'description' => 'Полезный витаминный коктейль', 'category' => 'exercise', 'energy_reward' => 18, 'experience_reward' => 8, 'cooldown_minutes' => 25, 'unlock_level' => 2, 'position' => 'kitchen', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Помыть посуду', 'description' => 'Навести чистоту', 'category' => 'social', 'energy_reward' => 8, 'experience_reward' => 5, 'cooldown_minutes' => 30, 'unlock_level' => 1, 'position' => 'kitchen', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Разобрать холодильник', 'description' => 'Проверить продукты', 'category' => 'social', 'energy_reward' => 10, 'experience_reward' => 7, 'cooldown_minutes' => 35, 'unlock_level' => 3, 'position' => 'kitchen', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Попробовать новый рецепт', 'description' => 'Приготовить блюдо, которое никогда не готовили', 'category' => 'creativity', 'energy_reward' => 24, 'experience_reward' => 18, 'cooldown_minutes' => 120, 'unlock_level' => 4, 'position' => 'kitchen', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Улучшить рецепт {{favorite_dish}}', 'description' => 'Добавить свой штрих к любимому блюду', 'category' => 'creativity', 'energy_reward' => 26, 'experience_reward' => 20, 'cooldown_minutes' => 90, 'unlock_level' => 5, 'position' => 'kitchen', 'is_active' => true, 'personalization_key' => 'favorite_dish'],
            ['name' => 'Приготовить домашний соус', 'description' => 'Песто, сальса или другой соус с нуля', 'category' => 'creativity', 'energy_reward' => 22, 'experience_reward' => 14, 'cooldown_minutes' => 120, 'unlock_level' => 6, 'position' => 'kitchen', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Приготовить {{favorite_dish}} для друга {{best_friend_name}}', 'description' => 'Твой друг {{best_friend_name}} будет рад попробовать твое блюдо', 'category' => 'social', 'energy_reward' => 30, 'experience_reward' => 22, 'cooldown_minutes' => 150, 'unlock_level' => 6, 'position' => 'kitchen', 'is_active' => true, 'personalization_key' => 'favorite_dish'],
            ['name' => 'Изучить историю {{favorite_dish}}', 'description' => 'Узнать происхождение любимого блюда', 'category' => 'creativity', 'energy_reward' => 14, 'experience_reward' => 16, 'cooldown_minutes' => 40, 'unlock_level' => 4, 'position' => 'kitchen', 'is_active' => true, 'personalization_key' => 'favorite_dish'],
            ['name' => 'Приготовить вариацию {{favorite_dish}}', 'description' => 'Создать новую версию любимого блюда', 'category' => 'creativity', 'energy_reward' => 25, 'experience_reward' => 19, 'cooldown_minutes' => 100, 'unlock_level' => 5, 'position' => 'kitchen', 'is_active' => true, 'personalization_key' => 'favorite_dish'],
            ['name' => 'Приготовить закуски', 'description' => 'Легкие закуски для перекуса', 'category' => 'exercise', 'energy_reward' => 16, 'experience_reward' => 9, 'cooldown_minutes' => 35, 'unlock_level' => 2, 'position' => 'kitchen', 'is_active' => true, 'personalization_key' => null],

            // ========== TABLE ==========
            ['name' => 'Позавтракать', 'description' => 'Спокойно поесть за столом', 'category' => 'exercise', 'energy_reward' => 25, 'experience_reward' => 8, 'cooldown_minutes' => 30, 'unlock_level' => 1, 'position' => 'table', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Попробовать {{favorite_dish}}', 'description' => 'Насладиться любимым блюдом', 'category' => 'exercise', 'energy_reward' => 22, 'experience_reward' => 10, 'cooldown_minutes' => 60, 'unlock_level' => 2, 'position' => 'table', 'is_active' => true, 'personalization_key' => 'favorite_dish'],
            ['name' => 'Написать письмо', 'description' => 'От руки, на бумаге', 'category' => 'creativity', 'energy_reward' => 12, 'experience_reward' => 15, 'cooldown_minutes' => 40, 'unlock_level' => 2, 'position' => 'table', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Написать письмо другу {{best_friend_name}}', 'description' => 'Твой друг {{best_friend_name}} будет рад получить письмо', 'category' => 'social', 'energy_reward' => 18, 'experience_reward' => 16, 'cooldown_minutes' => 50, 'unlock_level' => 3, 'position' => 'table', 'is_active' => true, 'personalization_key' => 'best_friend_name'],
            ['name' => 'Порешать кроссворд', 'description' => 'Головоломка за столом', 'category' => 'creativity', 'energy_reward' => 10, 'experience_reward' => 12, 'cooldown_minutes' => 35, 'unlock_level' => 1, 'position' => 'table', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Собрать пазл', 'description' => 'Несколько деталей', 'category' => 'relaxation', 'energy_reward' => 15, 'experience_reward' => 10, 'cooldown_minutes' => 45, 'unlock_level' => 3, 'position' => 'table', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Разложить карты', 'description' => 'Пасьянс для расслабления', 'category' => 'relaxation', 'energy_reward' => 12, 'experience_reward' => 6, 'cooldown_minutes' => 30, 'unlock_level' => 1, 'position' => 'table', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Сделать оригами', 'description' => 'Сложить бумажную фигурку', 'category' => 'creativity', 'energy_reward' => 14, 'experience_reward' => 14, 'cooldown_minutes' => 35, 'unlock_level' => 4, 'position' => 'table', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Навести порядок на столе', 'description' => 'Организовать пространство', 'category' => 'social', 'energy_reward' => 10, 'experience_reward' => 8, 'cooldown_minutes' => 25, 'unlock_level' => 1, 'position' => 'table', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Почитать книгу «{{favorite_book}}» за столом', 'description' => 'Спокойное чтение за чашкой чая', 'category' => 'relaxation', 'energy_reward' => 20, 'experience_reward' => 16, 'cooldown_minutes' => 60, 'unlock_level' => 2, 'position' => 'table', 'is_active' => true, 'personalization_key' => 'favorite_book'],
            ['name' => 'Поужинать с другом {{best_friend_name}}', 'description' => 'Твой друг {{best_friend_name}} будет рад провести время вместе', 'category' => 'social', 'energy_reward' => 28, 'experience_reward' => 20, 'cooldown_minutes' => 120, 'unlock_level' => 4, 'position' => 'table', 'is_active' => true, 'personalization_key' => 'best_friend_name'],
            ['name' => 'Поиграть в настольную игру', 'description' => 'Провести время за игрой', 'category' => 'social', 'energy_reward' => 18, 'experience_reward' => 12, 'cooldown_minutes' => 60, 'unlock_level' => 3, 'position' => 'table', 'is_active' => true, 'personalization_key' => null],

            // ========== WALLCLOCK ==========
            ['name' => 'Посмотреть на часы', 'description' => 'Проверить текущее время', 'category' => 'social', 'energy_reward' => 2, 'experience_reward' => 1, 'cooldown_minutes' => 5, 'unlock_level' => 1, 'position' => 'wallClock', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Подвести часы', 'description' => 'Настроить точное время', 'category' => 'social', 'energy_reward' => 5, 'experience_reward' => 4, 'cooldown_minutes' => 20, 'unlock_level' => 1, 'position' => 'wallClock', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Послушать тиканье', 'description' => 'Медитативное наблюдение', 'category' => 'relaxation', 'energy_reward' => 8, 'experience_reward' => 5, 'cooldown_minutes' => 15, 'unlock_level' => 2, 'position' => 'wallClock', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Запланировать день', 'description' => 'Рассчитать время на дела', 'category' => 'social', 'energy_reward' => 10, 'experience_reward' => 10, 'cooldown_minutes' => 30, 'unlock_level' => 1, 'position' => 'wallClock', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Подумать о времени', 'description' => 'Философские размышления', 'category' => 'creativity', 'energy_reward' => 12, 'experience_reward' => 12, 'cooldown_minutes' => 25, 'unlock_level' => 3, 'position' => 'wallClock', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Поменять батарейку', 'description' => 'Заменить элемент питания', 'category' => 'social', 'energy_reward' => 6, 'experience_reward' => 5, 'cooldown_minutes' => 15, 'unlock_level' => 2, 'position' => 'wallClock', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Протереть часы', 'description' => 'Очистить циферблат', 'category' => 'social', 'energy_reward' => 5, 'experience_reward' => 3, 'cooldown_minutes' => 10, 'unlock_level' => 1, 'position' => 'wallClock', 'is_active' => true, 'personalization_key' => null],

            // ========== LAPTOP ==========
            ['name' => 'Написать код', 'description' => 'Поработать над проектом', 'category' => 'social', 'energy_reward' => 15, 'experience_reward' => 20, 'cooldown_minutes' => 60, 'unlock_level' => 3, 'position' => 'laptop', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Проверить уведомления', 'description' => 'Просмотреть системные сообщения', 'category' => 'social', 'energy_reward' => 5, 'experience_reward' => 3, 'cooldown_minutes' => 15, 'unlock_level' => 1, 'position' => 'laptop', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Изучить что-то новое', 'description' => 'Посмотреть обучающий курс', 'category' => 'creativity', 'energy_reward' => 12, 'experience_reward' => 18, 'cooldown_minutes' => 50, 'unlock_level' => 3, 'position' => 'laptop', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Просмотреть видео о фильме «{{favorite_movie}}»', 'description' => 'Найти интересные факты о фильме', 'category' => 'creativity', 'energy_reward' => 14, 'experience_reward' => 12, 'cooldown_minutes' => 40, 'unlock_level' => 3, 'position' => 'laptop', 'is_active' => true, 'personalization_key' => 'favorite_movie'],
            ['name' => 'Найти информацию об авторе книги «{{favorite_book}}»', 'description' => 'Изучить биографию писателя', 'category' => 'creativity', 'energy_reward' => 13, 'experience_reward' => 15, 'cooldown_minutes' => 45, 'unlock_level' => 4, 'position' => 'laptop', 'is_active' => true, 'personalization_key' => 'favorite_book'],
            ['name' => 'Поработать над проектом', 'description' => 'Сосредоточиться на задаче', 'category' => 'creativity', 'energy_reward' => 18, 'experience_reward' => 20, 'cooldown_minutes' => 90, 'unlock_level' => 4, 'position' => 'laptop', 'is_active' => true, 'personalization_key' => null],

            // ========== FRIDGE ==========
            ['name' => 'Проверить холодильник', 'description' => 'Посмотреть что есть в наличии', 'category' => 'social', 'energy_reward' => 5, 'experience_reward' => 3, 'cooldown_minutes' => 15, 'unlock_level' => 1, 'position' => 'fridge', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Взять продукты для {{favorite_dish}}', 'description' => 'Подготовить ингредиенты для любимого блюда', 'category' => 'exercise', 'energy_reward' => 12, 'experience_reward' => 8, 'cooldown_minutes' => 30, 'unlock_level' => 2, 'position' => 'fridge', 'is_active' => true, 'personalization_key' => 'favorite_dish'],
            ['name' => 'Разобрать залежи', 'description' => 'Навести порядок в холодильнике', 'category' => 'social', 'energy_reward' => 10, 'experience_reward' => 7, 'cooldown_minutes' => 35, 'unlock_level' => 2, 'position' => 'fridge', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Составить список покупок', 'description' => 'Запланировать поход в магазин', 'category' => 'social', 'energy_reward' => 8, 'experience_reward' => 6, 'cooldown_minutes' => 25, 'unlock_level' => 1, 'position' => 'fridge', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Проверить сроки годности', 'description' => 'Убедиться что все свежее', 'category' => 'social', 'energy_reward' => 7, 'experience_reward' => 5, 'cooldown_minutes' => 20, 'unlock_level' => 2, 'position' => 'fridge', 'is_active' => true, 'personalization_key' => null],

            // ========== TRASHCAN ==========
            ['name' => 'Вынести мусор', 'description' => 'Навести порядок', 'category' => 'social', 'energy_reward' => 8, 'experience_reward' => 5, 'cooldown_minutes' => 30, 'unlock_level' => 1, 'position' => 'trashCan', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Разобрать мусор', 'description' => 'Разделить по категориям', 'category' => 'social', 'energy_reward' => 12, 'experience_reward' => 8, 'cooldown_minutes' => 40, 'unlock_level' => 2, 'position' => 'trashCan', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Очистить корзину', 'description' => 'Выбросить ненужное', 'category' => 'social', 'energy_reward' => 10, 'experience_reward' => 6, 'cooldown_minutes' => 25, 'unlock_level' => 1, 'position' => 'trashCan', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Разобрать вторсырье', 'description' => 'Подготовить к переработке', 'category' => 'social', 'energy_reward' => 11, 'experience_reward' => 7, 'cooldown_minutes' => 30, 'unlock_level' => 3, 'position' => 'trashCan', 'is_active' => true, 'personalization_key' => null],

            // ========== BED ==========
            ['name' => 'Полежать с книгой', 'description' => 'Почитать в кровати', 'category' => 'relaxation', 'energy_reward' => 20, 'experience_reward' => 15, 'cooldown_minutes' => 45, 'unlock_level' => 2, 'position' => 'bed', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Почитать книгу «{{favorite_book}}» в кровати', 'description' => 'Уютное чтение перед сном', 'category' => 'relaxation', 'energy_reward' => 22, 'experience_reward' => 18, 'cooldown_minutes' => 60, 'unlock_level' => 2, 'position' => 'bed', 'is_active' => true, 'personalization_key' => 'favorite_book'],
            ['name' => 'Отдохнуть', 'description' => 'Немного полежать', 'category' => 'relaxation', 'energy_reward' => 15, 'experience_reward' => 8, 'cooldown_minutes' => 30, 'unlock_level' => 1, 'position' => 'bed', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Послушать {{favorite_song}}', 'description' => 'Релакс под любимую музыку', 'category' => 'relaxation', 'energy_reward' => 18, 'experience_reward' => 10, 'cooldown_minutes' => 45, 'unlock_level' => 2, 'position' => 'bed', 'is_active' => true, 'personalization_key' => 'favorite_song'],
            ['name' => 'Подумать о друге {{best_friend_name}}', 'description' => 'Твой друг {{best_friend_name}} будет рад узнать что ты вспомнил о нем', 'category' => 'social', 'energy_reward' => 16, 'experience_reward' => 12, 'cooldown_minutes' => 35, 'unlock_level' => 2, 'position' => 'bed', 'is_active' => true, 'personalization_key' => 'best_friend_name'],
            ['name' => 'Медитировать', 'description' => 'Практика осознанности', 'category' => 'relaxation', 'energy_reward' => 20, 'experience_reward' => 12, 'cooldown_minutes' => 60, 'unlock_level' => 4, 'position' => 'bed', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Практика loving-kindness медитации', 'description' => 'Медитация любящей доброты к себе и другим', 'category' => 'relaxation', 'energy_reward' => 22, 'experience_reward' => 16, 'cooldown_minutes' => 120, 'unlock_level' => 6, 'position' => 'bed', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Ведение дневника', 'description' => 'Записать мысли дня', 'category' => 'creativity', 'energy_reward' => 14, 'experience_reward' => 12, 'cooldown_minutes' => 40, 'unlock_level' => 3, 'position' => 'bed', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Сделать легкую растяжку', 'description' => 'Расслабить мышцы перед сном', 'category' => 'exercise', 'energy_reward' => 16, 'experience_reward' => 9, 'cooldown_minutes' => 30, 'unlock_level' => 3, 'position' => 'bed', 'is_active' => true, 'personalization_key' => null],

            // ========== MIRROR ==========
            ['name' => 'Посмотреть в зеркало', 'description' => 'Проверить свой внешний вид', 'category' => 'social', 'energy_reward' => 5, 'experience_reward' => 3, 'cooldown_minutes' => 15, 'unlock_level' => 1, 'position' => 'mirror', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Сделать прическу', 'description' => 'Привести себя в порядок', 'category' => 'social', 'energy_reward' => 12, 'experience_reward' => 8, 'cooldown_minutes' => 30, 'unlock_level' => 1, 'position' => 'mirror', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Улыбнуться себе', 'description' => 'Позитивный настрой', 'category' => 'relaxation', 'energy_reward' => 10, 'experience_reward' => 6, 'cooldown_minutes' => 20, 'unlock_level' => 1, 'position' => 'mirror', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Практика аффирмаций', 'description' => 'Позитивные утверждения', 'category' => 'relaxation', 'energy_reward' => 15, 'experience_reward' => 12, 'cooldown_minutes' => 40, 'unlock_level' => 3, 'position' => 'mirror', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Протереть зеркало', 'description' => 'Навести чистоту', 'category' => 'social', 'energy_reward' => 8, 'experience_reward' => 5, 'cooldown_minutes' => 20, 'unlock_level' => 1, 'position' => 'mirror', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Поправить одежду', 'description' => 'Привести себя в порядок', 'category' => 'social', 'energy_reward' => 6, 'experience_reward' => 4, 'cooldown_minutes' => 15, 'unlock_level' => 1, 'position' => 'mirror', 'is_active' => true, 'personalization_key' => null],
            ['name' => 'Сделать массаж лица', 'description' => 'Расслабить мышцы лица', 'category' => 'relaxation', 'energy_reward' => 12, 'experience_reward' => 7, 'cooldown_minutes' => 25, 'unlock_level' => 2, 'position' => 'mirror', 'is_active' => true, 'personalization_key' => null],
        ];
    }
}

