<?php

namespace Database\Seeders;

use App\Models\MicroAction;
use Illuminate\Database\Seeder;

class MicroActionSeeder150 extends Seeder
{
    public function run(): void
    {
        $microActions = [
            [
                'name' => 'Проверить уведомления',
                'description' => 'Быстро просмотреть важные сообщения',
                'energy_reward' => 5,
                'experience_reward' => 2,
                'cooldown_minutes' => 15,
                'unlock_level' => 1,
                'category' => 'social',
                'position' => 'phone',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Послушать {{favorite_song}}',
                'description' => 'Включить любимый трек для настроения',
                'energy_reward' => 10,
                'experience_reward' => 3,
                'cooldown_minutes' => 20,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'phone',
                'is_active' => true,
                'personalization_key' => 'favorite_song',
            ],
            [
                'name' => 'Дыхательная практика',
                'description' => 'Использовать приложение для медитации',
                'energy_reward' => 15,
                'experience_reward' => 5,
                'cooldown_minutes' => 30,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'phone',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Фото для Instagram',
                'description' => 'Сделать креативное фото для соцсетей',
                'energy_reward' => 8,
                'experience_reward' => 4,
                'cooldown_minutes' => 45,
                'unlock_level' => 2,
                'category' => 'creativity',
                'position' => 'phone',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Позвонить {{best_friend_name}}',
                'description' => 'Короткий звонок близкому человеку',
                'energy_reward' => 12,
                'experience_reward' => 6,
                'cooldown_minutes' => 60,
                'unlock_level' => 1,
                'category' => 'social',
                'position' => 'phone',
                'is_active' => true,
                'personalization_key' => 'best_friend_name',
            ],
            [
                'name' => 'Мини-игра',
                'description' => 'Поиграть в расслабляющую игру 5 минут',
                'energy_reward' => 7,
                'experience_reward' => 3,
                'cooldown_minutes' => 25,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'phone',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Написать благодарность',
                'description' => 'Записать, за что вы благодарны сегодня',
                'energy_reward' => 10,
                'experience_reward' => 5,
                'cooldown_minutes' => 120,
                'unlock_level' => 2,
                'category' => 'creativity',
                'position' => 'phone',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Видео-шутка',
                'description' => 'Посмотреть короткое смешное видео',
                'energy_reward' => 6,
                'experience_reward' => 2,
                'cooldown_minutes' => 20,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'phone',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Мобильная йога',
                'description' => 'Короткая сессия йоги по видео',
                'energy_reward' => 15,
                'experience_reward' => 7,
                'cooldown_minutes' => 90,
                'unlock_level' => 3,
                'category' => 'exercise',
                'position' => 'phone',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Цифровой детокс',
                'description' => 'Включить режим "не беспокоить" на 30 минут',
                'energy_reward' => 20,
                'experience_reward' => 8,
                'cooldown_minutes' => 180,
                'unlock_level' => 4,
                'category' => 'relaxation',
                'position' => 'phone',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Голосовое сообщение',
                'description' => 'Отправить голосовую поддержку {{best_friend_name}}',
                'energy_reward' => 8,
                'experience_reward' => 4,
                'cooldown_minutes' => 40,
                'unlock_level' => 2,
                'category' => 'social',
                'position' => 'phone',
                'is_active' => true,
                'personalization_key' => 'best_friend_name',
            ],
            [
                'name' => 'Чек-лист дня',
                'description' => 'Составить список задач на день',
                'energy_reward' => 10,
                'experience_reward' => 5,
                'cooldown_minutes' => 240,
                'unlock_level' => 1,
                'category' => 'creativity',
                'position' => 'phone',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Фитнес-трекер',
                'description' => 'Проверить активность и сделать разминку',
                'energy_reward' => 12,
                'experience_reward' => 5,
                'cooldown_minutes' => 60,
                'unlock_level' => 2,
                'category' => 'exercise',
                'position' => 'phone',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Аудиокнига',
                'description' => 'Послушать главу из {{favorite_book}}',
                'energy_reward' => 15,
                'experience_reward' => 8,
                'cooldown_minutes' => 120,
                'unlock_level' => 3,
                'category' => 'relaxation',
                'position' => 'phone',
                'is_active' => true,
                'personalization_key' => 'favorite_book',
            ],
            [
                'name' => 'Мемы с друзьями',
                'description' => 'Обменяться смешными мемами с {{best_friend_name}}',
                'energy_reward' => 7,
                'experience_reward' => 3,
                'cooldown_minutes' => 30,
                'unlock_level' => 1,
                'category' => 'social',
                'position' => 'phone',
                'is_active' => true,
                'personalization_key' => 'best_friend_name',
            ],
            [
                'name' => 'Мини-викторина',
                'description' => 'Пройти короткий образовательный квиз',
                'energy_reward' => 9,
                'experience_reward' => 6,
                'cooldown_minutes' => 45,
                'unlock_level' => 2,
                'category' => 'creativity',
                'position' => 'phone',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Растяжка за столом',
                'description' => 'Упражнения для шеи и плеч',
                'energy_reward' => 15,
                'experience_reward' => 5,
                'cooldown_minutes' => 30,
                'unlock_level' => 1,
                'category' => 'exercise',
                'position' => 'table',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Выпить воды',
                'description' => 'Стакан воды для гидратации',
                'energy_reward' => 5,
                'experience_reward' => 2,
                'cooldown_minutes' => 45,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'table',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Упражнения для глаз',
                'description' => 'Снять напряжение с глаз после работы',
                'energy_reward' => 8,
                'experience_reward' => 3,
                'cooldown_minutes' => 20,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'table',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Набросать идеи',
                'description' => 'Записать 5 креативных идей на бумаге',
                'energy_reward' => 10,
                'experience_reward' => 7,
                'cooldown_minutes' => 60,
                'unlock_level' => 2,
                'category' => 'creativity',
                'position' => 'table',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Перекус фруктами',
                'description' => 'Съесть полезный перекус',
                'energy_reward' => 10,
                'experience_reward' => 3,
                'cooldown_minutes' => 90,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'table',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Массаж рук',
                'description' => 'Самомассаж кистей и пальцев',
                'energy_reward' => 12,
                'experience_reward' => 4,
                'cooldown_minutes' => 40,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'table',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Чайная пауза',
                'description' => 'Заварить и выпить успокаивающий чай',
                'energy_reward' => 15,
                'experience_reward' => 5,
                'cooldown_minutes' => 120,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'table',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Дудлинг',
                'description' => 'Порисовать абстрактные узоры',
                'energy_reward' => 10,
                'experience_reward' => 6,
                'cooldown_minutes' => 45,
                'unlock_level' => 2,
                'category' => 'creativity',
                'position' => 'table',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Письмо себе',
                'description' => 'Написать короткое письмо будущему себе',
                'energy_reward' => 12,
                'experience_reward' => 8,
                'cooldown_minutes' => 240,
                'unlock_level' => 3,
                'category' => 'creativity',
                'position' => 'table',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Настольная игра',
                'description' => 'Сыграть в быструю карточную игру',
                'energy_reward' => 15,
                'experience_reward' => 6,
                'cooldown_minutes' => 90,
                'unlock_level' => 2,
                'category' => 'social',
                'position' => 'table',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Оригами',
                'description' => 'Сложить простую фигурку из бумаги',
                'energy_reward' => 10,
                'experience_reward' => 7,
                'cooldown_minutes' => 60,
                'unlock_level' => 3,
                'category' => 'creativity',
                'position' => 'table',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Кроссворд',
                'description' => 'Решить несколько слов в кроссворде',
                'energy_reward' => 8,
                'experience_reward' => 5,
                'cooldown_minutes' => 45,
                'unlock_level' => 2,
                'category' => 'creativity',
                'position' => 'table',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Позитивные аффирмации',
                'description' => 'Прочитать вслух 3 аффирмации',
                'energy_reward' => 10,
                'experience_reward' => 4,
                'cooldown_minutes' => 60,
                'unlock_level' => 2,
                'category' => 'relaxation',
                'position' => 'table',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Упражнение для спины',
                'description' => 'Прогибы и наклоны сидя',
                'energy_reward' => 15,
                'experience_reward' => 6,
                'cooldown_minutes' => 40,
                'unlock_level' => 1,
                'category' => 'exercise',
                'position' => 'table',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Записать мечту',
                'description' => 'Описать одну свою мечту подробно',
                'energy_reward' => 12,
                'experience_reward' => 8,
                'cooldown_minutes' => 180,
                'unlock_level' => 3,
                'category' => 'creativity',
                'position' => 'table',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Дыхание 4-7-8',
                'description' => 'Практика успокаивающего дыхания',
                'energy_reward' => 15,
                'experience_reward' => 6,
                'cooldown_minutes' => 30,
                'unlock_level' => 2,
                'category' => 'relaxation',
                'position' => 'table',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Комедийный сериал',
                'description' => 'Посмотреть эпизод любимой комедии',
                'energy_reward' => 20,
                'experience_reward' => 5,
                'cooldown_minutes' => 120,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'tv',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Документальный фильм',
                'description' => 'Узнать что-то новое из документалки',
                'energy_reward' => 15,
                'experience_reward' => 10,
                'cooldown_minutes' => 180,
                'unlock_level' => 2,
                'category' => 'creativity',
                'position' => 'tv',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Танцевальное шоу',
                'description' => 'Посмотреть и потанцевать под TV',
                'energy_reward' => 18,
                'experience_reward' => 8,
                'cooldown_minutes' => 90,
                'unlock_level' => 2,
                'category' => 'exercise',
                'position' => 'tv',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Йога с видео',
                'description' => 'Практика йоги по видеоуроку',
                'energy_reward' => 25,
                'experience_reward' => 10,
                'cooldown_minutes' => 120,
                'unlock_level' => 3,
                'category' => 'exercise',
                'position' => 'tv',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Кулинарное шоу',
                'description' => 'Найти рецепт {{favorite_dish}}',
                'energy_reward' => 12,
                'experience_reward' => 6,
                'cooldown_minutes' => 60,
                'unlock_level' => 2,
                'category' => 'creativity',
                'position' => 'tv',
                'is_active' => true,
                'personalization_key' => 'favorite_dish',
            ],
            [
                'name' => 'Мотивационная речь',
                'description' => 'TED talk для вдохновения',
                'energy_reward' => 15,
                'experience_reward' => 9,
                'cooldown_minutes' => 90,
                'unlock_level' => 2,
                'category' => 'creativity',
                'position' => 'tv',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Семейный фильм',
                'description' => 'Посмотреть {{favorite_movie}} вместе с близкими',
                'energy_reward' => 20,
                'experience_reward' => 8,
                'cooldown_minutes' => 240,
                'unlock_level' => 1,
                'category' => 'social',
                'position' => 'tv',
                'is_active' => true,
                'personalization_key' => 'favorite_movie',
            ],
            [
                'name' => 'Караоке дома',
                'description' => 'Спеть {{favorite_song}}',
                'energy_reward' => 18,
                'experience_reward' => 7,
                'cooldown_minutes' => 120,
                'unlock_level' => 2,
                'category' => 'creativity',
                'position' => 'tv',
                'is_active' => true,
                'personalization_key' => 'favorite_song',
            ],
            [
                'name' => 'Фитнес-тренировка',
                'description' => 'Полноценная тренировка по видео',
                'energy_reward' => 25,
                'experience_reward' => 12,
                'cooldown_minutes' => 180,
                'unlock_level' => 3,
                'category' => 'exercise',
                'position' => 'tv',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Природные пейзажи',
                'description' => 'Релакс под видео природы',
                'energy_reward' => 15,
                'experience_reward' => 4,
                'cooldown_minutes' => 45,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'tv',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Игровое шоу',
                'description' => 'Поучаствовать виртуально в викторине',
                'energy_reward' => 12,
                'experience_reward' => 6,
                'cooldown_minutes' => 60,
                'unlock_level' => 1,
                'category' => 'social',
                'position' => 'tv',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Ретро-мультфильмы',
                'description' => 'Окунуться в детские воспоминания',
                'energy_reward' => 15,
                'experience_reward' => 5,
                'cooldown_minutes' => 90,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'tv',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Стретчинг перед TV',
                'description' => 'Растяжка всего тела',
                'energy_reward' => 20,
                'experience_reward' => 8,
                'cooldown_minutes' => 90,
                'unlock_level' => 2,
                'category' => 'exercise',
                'position' => 'tv',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Stand-up комедия',
                'description' => 'Посмеяться над выступлением комика',
                'energy_reward' => 18,
                'experience_reward' => 5,
                'cooldown_minutes' => 60,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'tv',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Путешествия по миру',
                'description' => 'Виртуальный тур по странам',
                'energy_reward' => 15,
                'experience_reward' => 8,
                'cooldown_minutes' => 90,
                'unlock_level' => 2,
                'category' => 'creativity',
                'position' => 'tv',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Концерт любимой группы',
                'description' => 'Посмотреть концерт исполнителя {{favorite_song}}',
                'energy_reward' => 20,
                'experience_reward' => 7,
                'cooldown_minutes' => 150,
                'unlock_level' => 2,
                'category' => 'relaxation',
                'position' => 'tv',
                'is_active' => true,
                'personalization_key' => 'favorite_song',
            ],
            [
                'name' => 'Проверить время',
                'description' => 'Узнать текущее время',
                'energy_reward' => 2,
                'experience_reward' => 1,
                'cooldown_minutes' => 5,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'wallClock',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Планирование дня',
                'description' => 'Оценить оставшееся время на задачи',
                'energy_reward' => 8,
                'experience_reward' => 5,
                'cooldown_minutes' => 60,
                'unlock_level' => 1,
                'category' => 'creativity',
                'position' => 'wallClock',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Таймер для перерыва',
                'description' => 'Запланировать отдых через 25 минут',
                'energy_reward' => 10,
                'experience_reward' => 4,
                'cooldown_minutes' => 90,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'wallClock',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Техника Помодоро',
                'description' => 'Начать 25-минутную сессию работы',
                'energy_reward' => 15,
                'experience_reward' => 8,
                'cooldown_minutes' => 120,
                'unlock_level' => 2,
                'category' => 'creativity',
                'position' => 'wallClock',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Медитация на время',
                'description' => 'Осознанность и принятие момента',
                'energy_reward' => 12,
                'experience_reward' => 6,
                'cooldown_minutes' => 60,
                'unlock_level' => 2,
                'category' => 'relaxation',
                'position' => 'wallClock',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Благодарность за день',
                'description' => 'Отметить, что успели сделать',
                'energy_reward' => 10,
                'experience_reward' => 5,
                'cooldown_minutes' => 180,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'wallClock',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Ритуал завершения',
                'description' => 'Завершить рабочий день символически',
                'energy_reward' => 15,
                'experience_reward' => 7,
                'cooldown_minutes' => 240,
                'unlock_level' => 2,
                'category' => 'relaxation',
                'position' => 'wallClock',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Напоминание о воде',
                'description' => 'Каждый час пить воду',
                'energy_reward' => 5,
                'experience_reward' => 2,
                'cooldown_minutes' => 60,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'wallClock',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Время для движения',
                'description' => 'Встать и размяться',
                'energy_reward' => 10,
                'experience_reward' => 4,
                'cooldown_minutes' => 45,
                'unlock_level' => 1,
                'category' => 'exercise',
                'position' => 'wallClock',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Отложенная награда',
                'description' => 'Запланировать приятное дело',
                'energy_reward' => 8,
                'experience_reward' => 4,
                'cooldown_minutes' => 120,
                'unlock_level' => 2,
                'category' => 'creativity',
                'position' => 'wallClock',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Email-детокс',
                'description' => 'Закрыть почту на час',
                'energy_reward' => 15,
                'experience_reward' => 6,
                'cooldown_minutes' => 180,
                'unlock_level' => 2,
                'category' => 'relaxation',
                'position' => 'lapTop',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Онлайн-курс',
                'description' => 'Пройти короткий урок',
                'energy_reward' => 12,
                'experience_reward' => 10,
                'cooldown_minutes' => 120,
                'unlock_level' => 2,
                'category' => 'creativity',
                'position' => 'lapTop',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Написать статью',
                'description' => 'Поработать над блогом',
                'energy_reward' => 15,
                'experience_reward' => 12,
                'cooldown_minutes' => 180,
                'unlock_level' => 3,
                'category' => 'creativity',
                'position' => 'lapTop',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Видеозвонок',
                'description' => 'Пообщаться с друзьями онлайн',
                'energy_reward' => 18,
                'experience_reward' => 8,
                'cooldown_minutes' => 120,
                'unlock_level' => 1,
                'category' => 'social',
                'position' => 'lapTop',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Фоторедактор',
                'description' => 'Отредактировать креативное фото',
                'energy_reward' => 12,
                'experience_reward' => 8,
                'cooldown_minutes' => 90,
                'unlock_level' => 2,
                'category' => 'creativity',
                'position' => 'lapTop',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Онлайн-игра с друзьями',
                'description' => 'Расслабиться за игрой',
                'energy_reward' => 15,
                'experience_reward' => 6,
                'cooldown_minutes' => 120,
                'unlock_level' => 2,
                'category' => 'social',
                'position' => 'lapTop',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Составить плейлист',
                'description' => 'Создать музыкальную подборку',
                'energy_reward' => 10,
                'experience_reward' => 5,
                'cooldown_minutes' => 60,
                'unlock_level' => 1,
                'category' => 'creativity',
                'position' => 'lapTop',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Почистить рабочий стол',
                'description' => 'Организовать файлы на компьютере',
                'energy_reward' => 10,
                'experience_reward' => 5,
                'cooldown_minutes' => 240,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'lapTop',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Цифровое искусство',
                'description' => 'Порисовать в графическом редакторе',
                'energy_reward' => 15,
                'experience_reward' => 10,
                'cooldown_minutes' => 120,
                'unlock_level' => 3,
                'category' => 'creativity',
                'position' => 'lapTop',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Вебинар',
                'description' => 'Поучаствовать в образовательном вебинаре',
                'energy_reward' => 12,
                'experience_reward' => 10,
                'cooldown_minutes' => 180,
                'unlock_level' => 2,
                'category' => 'creativity',
                'position' => 'lapTop',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Социальные сети',
                'description' => 'Проверить новости друзей',
                'energy_reward' => 8,
                'experience_reward' => 3,
                'cooldown_minutes' => 45,
                'unlock_level' => 1,
                'category' => 'social',
                'position' => 'lapTop',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Написать код',
                'description' => 'Поработать над личным проектом',
                'energy_reward' => 15,
                'experience_reward' => 12,
                'cooldown_minutes' => 180,
                'unlock_level' => 4,
                'category' => 'creativity',
                'position' => 'lapTop',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Медитация онлайн',
                'description' => 'Гайд медитация через браузер',
                'energy_reward' => 18,
                'experience_reward' => 7,
                'cooldown_minutes' => 90,
                'unlock_level' => 2,
                'category' => 'relaxation',
                'position' => 'lapTop',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Портфолио',
                'description' => 'Обновить профессиональное портфолио',
                'energy_reward' => 12,
                'experience_reward' => 10,
                'cooldown_minutes' => 240,
                'unlock_level' => 3,
                'category' => 'creativity',
                'position' => 'lapTop',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Форум по интересам',
                'description' => 'Пообщаться в тематическом сообществе',
                'energy_reward' => 10,
                'experience_reward' => 6,
                'cooldown_minutes' => 60,
                'unlock_level' => 2,
                'category' => 'social',
                'position' => 'lapTop',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Виртуальный музей',
                'description' => 'Посетить онлайн-выставку',
                'energy_reward' => 15,
                'experience_reward' => 9,
                'cooldown_minutes' => 120,
                'unlock_level' => 2,
                'category' => 'creativity',
                'position' => 'lapTop',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Достать полезный перекус',
                'description' => 'Взять фрукты или орехи',
                'energy_reward' => 10,
                'experience_reward' => 3,
                'cooldown_minutes' => 120,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'fridge',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Выпить холодной воды',
                'description' => 'Освежиться прохладной водой',
                'energy_reward' => 8,
                'experience_reward' => 2,
                'cooldown_minutes' => 60,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'fridge',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Проверить продукты',
                'description' => 'Посмотреть, что есть вкусного',
                'energy_reward' => 5,
                'experience_reward' => 2,
                'cooldown_minutes' => 45,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'fridge',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Смузи-награда',
                'description' => 'Приготовить полезный смузи',
                'energy_reward' => 15,
                'experience_reward' => 6,
                'cooldown_minutes' => 180,
                'unlock_level' => 2,
                'category' => 'creativity',
                'position' => 'fridge',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Свежий сок',
                'description' => 'Выжать фреш из фруктов',
                'energy_reward' => 12,
                'experience_reward' => 5,
                'cooldown_minutes' => 150,
                'unlock_level' => 2,
                'category' => 'relaxation',
                'position' => 'fridge',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Организовать холодильник',
                'description' => 'Навести порядок на полках',
                'energy_reward' => 10,
                'experience_reward' => 5,
                'cooldown_minutes' => 240,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'fridge',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Протеиновый перекус',
                'description' => 'Йогурт или творог для энергии',
                'energy_reward' => 12,
                'experience_reward' => 4,
                'cooldown_minutes' => 150,
                'unlock_level' => 2,
                'category' => 'exercise',
                'position' => 'fridge',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Список покупок',
                'description' => 'Записать, что нужно купить',
                'energy_reward' => 8,
                'experience_reward' => 4,
                'cooldown_minutes' => 180,
                'unlock_level' => 1,
                'category' => 'creativity',
                'position' => 'fridge',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Ледяная маска',
                'description' => 'Приложить лед к лицу для свежести',
                'energy_reward' => 10,
                'experience_reward' => 4,
                'cooldown_minutes' => 120,
                'unlock_level' => 2,
                'category' => 'relaxation',
                'position' => 'fridge',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Приготовить салат',
                'description' => 'Быстрый витаминный салат',
                'energy_reward' => 15,
                'experience_reward' => 7,
                'cooldown_minutes' => 180,
                'unlock_level' => 2,
                'category' => 'creativity',
                'position' => 'fridge',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Выбросить мусор',
                'description' => 'Вынести накопившийся мусор',
                'energy_reward' => 8,
                'experience_reward' => 3,
                'cooldown_minutes' => 120,
                'unlock_level' => 1,
                'category' => 'exercise',
                'position' => 'trashCan',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Разобрать бумаги',
                'description' => 'Выкинуть ненужные документы',
                'energy_reward' => 10,
                'experience_reward' => 4,
                'cooldown_minutes' => 60,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'trashCan',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Цифровая уборка',
                'description' => 'Удалить старые файлы',
                'energy_reward' => 12,
                'experience_reward' => 5,
                'cooldown_minutes' => 180,
                'unlock_level' => 2,
                'category' => 'relaxation',
                'position' => 'trashCan',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Освободить место',
                'description' => 'Убрать лишние вещи с рабочего места',
                'energy_reward' => 15,
                'experience_reward' => 6,
                'cooldown_minutes' => 90,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'trashCan',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Избавиться от токсичных мыслей',
                'description' => 'Символически выкинуть негатив',
                'energy_reward' => 15,
                'experience_reward' => 7,
                'cooldown_minutes' => 120,
                'unlock_level' => 2,
                'category' => 'relaxation',
                'position' => 'trashCan',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Сортировка мусора',
                'description' => 'Разделить мусор для переработки',
                'energy_reward' => 10,
                'experience_reward' => 5,
                'cooldown_minutes' => 240,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'trashCan',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Очистка email',
                'description' => 'Удалить спам и старые письма',
                'energy_reward' => 12,
                'experience_reward' => 5,
                'cooldown_minutes' => 180,
                'unlock_level' => 2,
                'category' => 'relaxation',
                'position' => 'trashCan',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Минимализм',
                'description' => 'Избавиться от 3 ненужных вещей',
                'energy_reward' => 12,
                'experience_reward' => 6,
                'cooldown_minutes' => 240,
                'unlock_level' => 2,
                'category' => 'relaxation',
                'position' => 'trashCan',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Уборка рабочей зоны',
                'description' => 'Быстро привести в порядок стол',
                'energy_reward' => 10,
                'experience_reward' => 4,
                'cooldown_minutes' => 90,
                'unlock_level' => 1,
                'category' => 'exercise',
                'position' => 'trashCan',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Журнал избавлений',
                'description' => 'Записать, от чего избавились',
                'energy_reward' => 8,
                'experience_reward' => 5,
                'cooldown_minutes' => 120,
                'unlock_level' => 2,
                'category' => 'creativity',
                'position' => 'trashCan',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Короткий сон',
                'description' => 'Вздемнуть 15-20 минут',
                'energy_reward' => 25,
                'experience_reward' => 5,
                'cooldown_minutes' => 240,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'bed',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Медитация лежа',
                'description' => 'Расслабляющая медитация в постели',
                'energy_reward' => 20,
                'experience_reward' => 8,
                'cooldown_minutes' => 120,
                'unlock_level' => 2,
                'category' => 'relaxation',
                'position' => 'bed',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Визуализация целей',
                'description' => 'Представить свои достижения',
                'energy_reward' => 15,
                'experience_reward' => 8,
                'cooldown_minutes' => 180,
                'unlock_level' => 2,
                'category' => 'creativity',
                'position' => 'bed',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Дневник сновидений',
                'description' => 'Записать утренний сон',
                'energy_reward' => 10,
                'experience_reward' => 6,
                'cooldown_minutes' => 240,
                'unlock_level' => 2,
                'category' => 'creativity',
                'position' => 'bed',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Чтение в постели',
                'description' => 'Почитать главу из {{favorite_book}}',
                'energy_reward' => 18,
                'experience_reward' => 7,
                'cooldown_minutes' => 120,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'bed',
                'is_active' => true,
                'personalization_key' => 'favorite_book',
            ],
            [
                'name' => 'Утренняя растяжка',
                'description' => 'Потянуться сразу после пробуждения',
                'energy_reward' => 15,
                'experience_reward' => 5,
                'cooldown_minutes' => 240,
                'unlock_level' => 1,
                'category' => 'exercise',
                'position' => 'bed',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Упражнения в кровати',
                'description' => 'Легкая гимнастика лежа',
                'energy_reward' => 12,
                'experience_reward' => 5,
                'cooldown_minutes' => 180,
                'unlock_level' => 2,
                'category' => 'exercise',
                'position' => 'bed',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Прогрессивная релаксация',
                'description' => 'Расслабление каждой части тела',
                'energy_reward' => 20,
                'experience_reward' => 8,
                'cooldown_minutes' => 120,
                'unlock_level' => 2,
                'category' => 'relaxation',
                'position' => 'bed',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Благодарность перед сном',
                'description' => 'Вспомнить 3 хороших момента дня',
                'energy_reward' => 15,
                'experience_reward' => 6,
                'cooldown_minutes' => 240,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'bed',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Аудиомедитация',
                'description' => 'Гайд медитация перед сном',
                'energy_reward' => 20,
                'experience_reward' => 7,
                'cooldown_minutes' => 240,
                'unlock_level' => 2,
                'category' => 'relaxation',
                'position' => 'bed',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Подушечная йога',
                'description' => 'Мягкие позы йоги в кровати',
                'energy_reward' => 18,
                'experience_reward' => 7,
                'cooldown_minutes' => 150,
                'unlock_level' => 2,
                'category' => 'exercise',
                'position' => 'bed',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Сменить постельное белье',
                'description' => 'Приятные ощущения от свежего белья',
                'energy_reward' => 12,
                'experience_reward' => 4,
                'cooldown_minutes' => 300,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'bed',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Ароматерапия',
                'description' => 'Использовать расслабляющие ароматы',
                'energy_reward' => 15,
                'experience_reward' => 5,
                'cooldown_minutes' => 180,
                'unlock_level' => 2,
                'category' => 'relaxation',
                'position' => 'bed',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Планирование завтра',
                'description' => 'Спокойно продумать планы',
                'energy_reward' => 10,
                'experience_reward' => 6,
                'cooldown_minutes' => 240,
                'unlock_level' => 1,
                'category' => 'creativity',
                'position' => 'bed',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Любовное письмо себе',
                'description' => 'Написать себе поддерживающие слова',
                'energy_reward' => 15,
                'experience_reward' => 8,
                'cooldown_minutes' => 240,
                'unlock_level' => 3,
                'category' => 'creativity',
                'position' => 'bed',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Шавасана',
                'description' => 'Поза трупа для глубокого расслабления',
                'energy_reward' => 20,
                'experience_reward' => 7,
                'cooldown_minutes' => 120,
                'unlock_level' => 2,
                'category' => 'relaxation',
                'position' => 'bed',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Позитивная аффирмация',
                'description' => 'Посмотреть в зеркало и сказать себе комплимент',
                'energy_reward' => 10,
                'experience_reward' => 5,
                'cooldown_minutes' => 60,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'mirror',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Улыбка себе',
                'description' => 'Улыбнуться своему отражению',
                'energy_reward' => 8,
                'experience_reward' => 3,
                'cooldown_minutes' => 30,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'mirror',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Уход за кожей',
                'description' => 'Нанести крем и сделать массаж лица',
                'energy_reward' => 15,
                'experience_reward' => 6,
                'cooldown_minutes' => 120,
                'unlock_level' => 2,
                'category' => 'relaxation',
                'position' => 'mirror',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Гимнастика для лица',
                'description' => 'Упражнения для тонуса кожи',
                'energy_reward' => 12,
                'experience_reward' => 5,
                'cooldown_minutes' => 90,
                'unlock_level' => 2,
                'category' => 'exercise',
                'position' => 'mirror',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Проверить осанку',
                'description' => 'Выпрямить спину и плечи',
                'energy_reward' => 10,
                'experience_reward' => 4,
                'cooldown_minutes' => 45,
                'unlock_level' => 1,
                'category' => 'exercise',
                'position' => 'mirror',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Практика мимики',
                'description' => 'Поработать над выражением лица',
                'energy_reward' => 8,
                'experience_reward' => 5,
                'cooldown_minutes' => 60,
                'unlock_level' => 2,
                'category' => 'creativity',
                'position' => 'mirror',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Примерка образов',
                'description' => 'Попробовать новый стиль',
                'energy_reward' => 12,
                'experience_reward' => 6,
                'cooldown_minutes' => 120,
                'unlock_level' => 2,
                'category' => 'creativity',
                'position' => 'mirror',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Селфи дня',
                'description' => 'Сделать фото для памяти',
                'energy_reward' => 8,
                'experience_reward' => 3,
                'cooldown_minutes' => 240,
                'unlock_level' => 1,
                'category' => 'creativity',
                'position' => 'mirror',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Утренний ритуал',
                'description' => 'Настроиться на продуктивный день',
                'energy_reward' => 15,
                'experience_reward' => 6,
                'cooldown_minutes' => 240,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'mirror',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Контакт с собой',
                'description' => 'Посмотреть себе в глаза и понять свои чувства',
                'energy_reward' => 12,
                'experience_reward' => 8,
                'cooldown_minutes' => 90,
                'unlock_level' => 3,
                'category' => 'relaxation',
                'position' => 'mirror',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Танец перед зеркалом',
                'description' => 'Свободное движение под музыку',
                'energy_reward' => 18,
                'experience_reward' => 7,
                'cooldown_minutes' => 90,
                'unlock_level' => 2,
                'category' => 'exercise',
                'position' => 'mirror',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Проверка языка тела',
                'description' => 'Отработать уверенную позу',
                'energy_reward' => 10,
                'experience_reward' => 6,
                'cooldown_minutes' => 60,
                'unlock_level' => 2,
                'category' => 'social',
                'position' => 'mirror',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Благодарность себе',
                'description' => 'Поблагодарить себя за сегодняшний день',
                'energy_reward' => 15,
                'experience_reward' => 7,
                'cooldown_minutes' => 240,
                'unlock_level' => 2,
                'category' => 'relaxation',
                'position' => 'mirror',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Макияж-терапия',
                'description' => 'Креативный макияж для настроения',
                'energy_reward' => 12,
                'experience_reward' => 6,
                'cooldown_minutes' => 180,
                'unlock_level' => 2,
                'category' => 'creativity',
                'position' => 'mirror',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Речевая практика',
                'description' => 'Репетиция важного разговора',
                'energy_reward' => 10,
                'experience_reward' => 7,
                'cooldown_minutes' => 120,
                'unlock_level' => 3,
                'category' => 'social',
                'position' => 'mirror',
                'is_active' => true,
                'personalization_key' => null,
            ],
            [
                'name' => 'Смех-терапия',
                'description' => 'Посмеяться над своим отражением',
                'energy_reward' => 12,
                'experience_reward' => 5,
                'cooldown_minutes' => 60,
                'unlock_level' => 1,
                'category' => 'relaxation',
                'position' => 'mirror',
                'is_active' => true,
                'personalization_key' => null,
            ],
        ];

        foreach ($microActions as $action) {
            MicroAction::updateOrCreate(
                ['name' => $action['name']],
                $action
            );
        }
        
        $this->command->info('Создано/обновлено ' . count($microActions) . ' микро-действий');
        $personalizedCount = collect($microActions)->whereNotNull('personalization_key')->count();
        $this->command->info('Из них с персонализацией: ' . $personalizedCount);
    }
}

