services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: tamagotchi-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./.env.docker:/var/www/html/.env:ro
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    env_file:
      - .env.docker
    expose:
      - "9000"
    networks:
      - tamagotchi-network
    depends_on:
      - nginx
    extra_hosts:
      - "db-host:81.19.135.205"

  nginx:
    image: nginx:1.25-alpine
    container_name: tamagotchi-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html/public:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/ssl:/etc/nginx/ssl:ro
    networks:
      - tamagotchi-network

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: tamagotchi-scheduler
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./.env.docker:/var/www/html/.env:ro
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    env_file:
      - .env.docker
    command: php artisan schedule:work
    networks:
      - tamagotchi-network
    depends_on:
      - app

  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile  
      target: production
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./.env.docker:/var/www/html/.env:ro
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    env_file:
      - .env.docker
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    networks:
      - tamagotchi-network
    depends_on:
      - app
    deploy:
      replicas: 2

networks:
  tamagotchi-network:
    driver: bridge

volumes:
  app-storage:
    driver: local
